spring:
  datasource:
    driver-class-name: org.firebirdsql.jdbc.FBDriver
#    url: jdbc:firebirdsql://192.168.2.11:3050//work/cmn/db/uvfs3/uvfswes.fdb?sql_dialect=3&charSet=utf-8
    url: jdbc:firebirdsql://localhost:3050//wrkdt/db/firebd/trtovswes.fdb?sql_dialect=3&charSet=utf-8
#    url: jdbc:firebirdsql://192.168.2.11:3050//work/cmn/db/trtovs/trtovswes.fdb?sql_dialect=3&charSet=utf-8
#    url: jdbc:firebirdsql://localhost:3050//wrkdt/db/firebd/trtovswes.fdb?sql_dialect=3&charSet=utf-8
#    url: jdbc:firebirdsql://localhost:3050//home/alexey/workspace/db/uvfs/uvfswes.fdb?sql_dialect=3&charSet=utf-8
    username: SYSDBA
#    password: masterkey
    password: masterskey
    useUnicode: true
    characterEncoding: UTF-8
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
  thymeleaf:
    cache : false
#
#
    welcome:
      message: "Hello Thymeleaf"
    error:
      message: "Module name and descr required"
